apiVersion: v1
kind: Service
metadata:
  name: nextcloud-server-lb
  labels:
    app: nextcloud
spec:
  selector:
    pod-label: nextcloud-server-pod
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  
 
